### ISSUE TITLE
KIT dataset labels 

### ISSUE THREAD

**Issue by h-bouzid** [zgzxy001/STMT#1]
Hi,

First, congratulations on the great work you did on "STMT" paper. 

I have a question on the labels used in the KIT dataset. when I tried generating the mocap KIT data, I couldn't extract the correct labels. 

I tried to extract them from the name of the "npz" files, eg. "bend_left09_poses.npz" ---> "bend_left" but i end up with more than 300 classes of 10 to 20 clip. Could you please provide me with the annotation method you used. 

Thanks a lot for you help.

**Comment by zgzxy001** [comment]
Hi, thank you very much for your interest. We extracted the labels from BABEL annotation file: https://babel.is.tue.mpg.de/data.html. Besides, we only keep single-class sequences following the existing practice of SOTA methods for 3D action recognition.

**Comment by h-bouzid** [comment]
And, for example in this annotation, which one of these features did you consider as your label: 
is it "['seq_ann']['labels'][0]['proc_label']" or do you use "['seq_ann']['labels'][0]['act_cat']" because sometimes they are different


![image](https://github.com/zgzxy001/STMT/assets/94684114/7dadb264-1872-434a-a886-262bf6ec310d)

Again, thank you for your time.

**Comment by zgzxy001** [comment]
Hi, we used "act_cat" as the label.
