### ISSUE TITLE
How to obtain mesh data from babel and kit

### ISSUE THREAD

**Issue by DeVriesMatt** [zgzxy001/STMT#2]
Hi, great work!

I am trying to obtain the mesh data from Babel and KIT datasets. What process did you follow to get this? It seems like there are quite a few steps that aren't easy to find online?

**Comment by zgzxy001** [comment]
Hi, thank you very much for your interest! We followed the [AMASS Tutorial](https://github.com/nghorbani/amass/blob/master/notebooks/01-AMASS_Visualization.ipynb) to save meshes. I updated the code to save meshes for a single sequence, including [exporting](https://github.com/zgzxy001/STMT/blob/master/data/save_obj_single.py) and [resizing](https://github.com/zgzxy001/STMT/blob/master/data/blender_process.py). I will try to push the batch processing code in March. Thanks!

**Comment by DeVriesMatt** [comment]
Thanks so much for the quick response!

**Comment by DeVriesMatt** [comment]
Sorry, another thing: where did you download the data like this from? /amass/data/BABEL/3d_obj/raw/KIT/917/Experiment3a_04_poses.npz

**Comment by zgzxy001** [comment]
Hi, the npz file comes from [AMASS](https://amass.is.tue.mpg.de/index.html) and the annotations come from [BABEL](https://babel.is.tue.mpg.de/data.html).
