### ISSUE TITLE
BABEL dataset Point Cloud format

### ISSUE THREAD

**Issue by wml666666** [zgzxy001/STMT#3]
Hello, may I ask how to obtain the Point Cloud format of the BABEL dataset? I only found his bone format data on the BABEL dataset official website.

**Comment by zgzxy001** [comment]
Hi, we have a [script](https://github.com/zgzxy001/STMT/blob/master/data/save_obj_single.py) to convert npz file to obj file, which is represented as a 3D mesh. You can save the mesh's vertices and use them as point clouds.

**Comment by wml666666** [comment]
> Hi, we have a [script](https://github.com/zgzxy001/STMT/blob/master/data/save_obj_single.py) to convert npz file to obj file, which is represented as a 3D mesh. You can save the mesh's vertices and use them as point clouds.

Thank you for your answer. I have reviewed the script file you mentioned, but there are several paths in the script file that I don't know where to download from:
support_dir = '/home/xiaoyu/src/amass/support_data/'
bm_fname = osp.join(support_dir, 'body_models/smplh/{}/model.npz'.format(subject_gender))
dmpl_fname = osp.join(support_dir, 'body_models/dmpls/{}/model.npz'.format(subject_gender))

**Comment by zgzxy001** [comment]
The other files are available in this repo: https://github.com/nghorbani/amass/blob/master/notebooks/01-AMASS_Visualization.ipynb.

**Comment by wml666666** [comment]
> The other files are available in this repo: https://github.com/nghorbani/amass/blob/master/notebooks/01-AMASS_Visualization.ipynb.

Thank you for your reply. We have downloaded the data. There are some parameters in the script file save_obj_single.py, such as -- class name 6-- outputname 1b00442c-ff1a-4675-8d73-21e680545819-- start_ts 110.382-- end_ts 112.167. We do not understand the settings of these parameters. There is also an error message "bm=BodyModel (bm_path=bm_fname, model_type=" smplh ", num'betas=num'betas, num_dmpls=num_dmpls, path_dmpl=dmpl_fname). to (comp_device)". Can you provide the environment for the package you installed? Thank you

**Comment by zgzxy001** [comment]
Hello, sorry for the late response. The class name is the class index, outputname is the name for the outputfile, start_ts is the start of the motion caption sequence, end_ts is the end of the motion caption sequence. Those fields are available at the original BABEL dataset (please refer to the data format section in [BABEL](https://babel.is.tue.mpg.de/data.html)). The BodyModel can be installed via [Human Body Prior](https://github.com/nghorbani/human_body_prior), you can follow the instructions of [AMASS ](https://github.com/nghorbani/amass?tab=readme-ov-file#installation)to install the dependencies. Feel free to reopen if you have any questions. Thanks!
